{
 "title": "Microservices Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "Application Logs (service.name)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Traces (Jaeger)",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "[Ouvrir Jaeger](http://localhost:16686)"
   }
  },
  {
   "title": "Orders Processed (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(orders_processed_total[5m])",
     "legendFormat": "orders"
    }
   ]
  },
  {
   "title": "Payments Processed (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(payments_processed_total[5m])",
     "legendFormat": "payments"
    }
   ]
  },
  {
   "title": "Notifications Sent (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rate(notifications_sent_total[5m])",
     "legendFormat": "notifications"
    }
   ]
  },
  {
   "title": "Order Processing Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(orders_processing_duration_seconds_sum[5m]) / rate(orders_processing_duration_seconds_count[5m])",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}